### ISSUE TITLE
Theme for Alacritty?

### ISSUE THREAD

**Issue by dotzenith** [Jean-Tinland/vscode-theme-night-shift#9]
I absolutely love this theme and I was wondering if you'd be willing to port it to Alacritty (terminal emulator)?

**Comment by Jean-Tinland** [comment]
Hi ! Yeah, I'll look into it! :)

**Comment by Jean-Tinland** [comment]
You'll find below a first draft you can paste in your `.alacritty.yml`, let me know if it is ok. Do not hesitate to let me know if I can improve it in any way! :)

```yml
# Colors (Night Shift)
colors:
  primary:
    background: "#1e2737"
    foreground: "#fff9ee"
  search:
    matches:
      foreground: "#1e2737"
      background: "#fff9ee"
    focused_match:
      foreground: "#1e2737"
      background: "#7eddde"
    bar:
      background: "#ffd484"
      foreground: "#1e2737"
  hints:
    start:
      foreground: "#1e2737"
      background: "#fff9ee"
    end:
      foreground: "#fff9ee"
      background: "#1e2737"
  normal:
    black: "#1e2737"
    red: "#e78482"
    green: "#8fc8bb"
    yellow: "#ffd484"
    blue: "#6db3ce"
    magenta: "#ad82cb"
    cyan: "#7eddde"
    white: "#f5f5f5"
  bright:
    black: "#1e2737"
    red: "#e78482"
    green: "#8fc8bb"
    yellow: "#ffd484"
    blue: "#6db3ce"
    magenta: "#ad82cb"
    cyan: "#7eddde"
    white: "#f5f5f5"
```
